name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
#  schedule:
#    - cron: '42 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
    - name: Build step
      run: |
        echo This is the placeholder for the compilation step
        ls -l something_that_does_not_Exist

  test:
    runs-on: ubuntu-latest
    name: Test
    needs: [build]

    steps:
    - name: Test step
      run: |
        echo This job only runs if the build job was successful



