name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
#  schedule:
#    - cron: '42 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
    - name: Build step
      run: |
        echo This is the placeholder for the compilation step
        echo "Enable the next line if you'd like to see what happens when the job fails."
        # ls -l something_that_does_not_Exist

  test:
    runs-on: ubuntu-latest
    name: Test
    needs: [build]

    steps:
    - name: Test step
      run: |
        echo This job only runs if the build job was successful

  linter:
    runs-on: ubuntu-latest
    name: Linter

    steps:
    - name: Linter step
      run: |
        echo This job is independent from the other, it can run in parallel to either the build job or the test-job

  run-generate:
    needs: [linter, test]
    uses: ./.github/workflows/generate.yaml

