name: Generate

on:
  push:
  pull_request:
  workflow_dispatch:
#  schedule:
#    - cron: '42 5 * * *'

jobs:
  empty:
    runs-on: ubuntu-latest
    name: Empty
    steps:
    - name: Empty
      run: |
        echo Empty


  generate:
    runs-on: ubuntu-latest
    name: Generate
    needs: [linter, test]

    steps:
    - name: Generate
      run: |
        echo This job only runs if both the linter and the test jobs were successful



