name: Generate

on:
  workflow_call:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate

    steps:
    - name: Generate
      run: |
        echo This job only runs if both the linter and the test jobs were successful.
        echo This is set in the ci.yaml file calling this file

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: [generate]

    steps:
    - name: Deploy
      run: |
        echo This job only runs if the Generate job was successful.

